services:
  - type: web
    name: sai-raju-portfolio
    env: node
    plan: free
    branch: main
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
        sync: true
